# Generated by Django 4.1.1 on 2022-09-11 21:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_task_author_alter_project_members_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("T", "Todo"), ("I", "In Progress"), ("D", "Done")],
                default="T",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="assignees",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_tasks", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
